### ISSUE TITLE
[개선] 통계 drawer 추가 및 상세 페이지 생성

### ISSUE THREAD

**Issue by yehey-1030** [yehey-1030/household-ledger-web#4]
### Todo

- [x] 통계 drawer 추가
- [x] 내역 타입에 따른 통계 페이지 추가
- [x] 통계 상세 페이지 추가
- [x] 헤더 디자인 수정 반영
